use_frameworks!       #使用frameworks
inhibit_all_warnings! #屏蔽警告

platform :ios, '8.0'

target 'SJM3u8MediaCache_Example' do
  pod 'SJM3u8MediaCache', :path => '../'

  target 'SJM3u8MediaCache_Tests' do
    inherit! :search_paths

    
  end
end
